steps:
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p /go/pkg && cd /go/pkg && gsutil cat gs://$PROJECT_ID-cache/anyvendor/anyvendor-mod.tar.gz | tar -xzf -']
  env:
  volumes: &vol
  - name: 'gopath'
    path: '/go/pkg'
  id: 'untar-mod-cache'

- name: 'golang:1.13'
  args: ['go', 'mod', 'download']
  volumes: *vol
  id: 'download'

- name: 'golang:1.13'
  args: ['go', 'mod', 'tidy']
  volumes: *vol
  id: 'tidy'

- name: 'golang:1.13'
  entrypoint: 'bash'
  volumes: *vol
  args: ['-c', ' cd /go/pkg && tar -zvcf anyvendor-mod.tar.gz mod']
  id: 'tar-cache'

- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '/go/pkg/anyvendor-mod.tar.gz', 'gs://$PROJECT_ID-cache/anyvendor/anyvendor-mod.tar.gz']
  volumes: *vol
  id: 'upload-cache'

options:
    env:
    - "GO111MODULE=on"